### ISSUE TITLE
crashed!

### ISSUE THREAD

**Issue by andyyuan78** [asrivat1/DeepLearningVideoGames#10]
envy@ub1404:/media/envy/data1t/os_prj/github/_deepmind/DeepLearningVideoGames$ python deep_q_network.py 
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice/tensor_name, save/restore_slice/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_2 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_2/tensor_name, save/restore_slice_2/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_1 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_1/tensor_name, save/restore_slice_1/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_3 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_3/tensor_name, save/restore_slice_3/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_4 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_4/tensor_name, save/restore_slice_4/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_5 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_5/tensor_name, save/restore_slice_5/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_6 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_6/tensor_name, save/restore_slice_6/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_12 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_12/tensor_name, save/restore_slice_12/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_7 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_7/tensor_name, save/restore_slice_7/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_8 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_8/tensor_name, save/restore_slice_8/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_9 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_9/tensor_name, save/restore_slice_9/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_10 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_10/tensor_name, save/restore_slice_10/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_11 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_11/tensor_name, save/restore_slice_11/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_31 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_31/tensor_name, save/restore_slice_31/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_13 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_13/tensor_name, save/restore_slice_13/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_14 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_14/tensor_name, save/restore_slice_14/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_15 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_15/tensor_name, save/restore_slice_15/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_16 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_16/tensor_name, save/restore_slice_16/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_17 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_17/tensor_name, save/restore_slice_17/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_18 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_18/tensor_name, save/restore_slice_18/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_19 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_19/tensor_name, save/restore_slice_19/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_20 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_20/tensor_name, save/restore_slice_20/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_21 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_21/tensor_name, save/restore_slice_21/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_28 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_28/tensor_name, save/restore_slice_28/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_23 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_23/tensor_name, save/restore_slice_23/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_24 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_24/tensor_name, save/restore_slice_24/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_25 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_25/tensor_name, save/restore_slice_25/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_26 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_26/tensor_name, save/restore_slice_26/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_22 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_22/tensor_name, save/restore_slice_22/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_29 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_29/tensor_name, save/restore_slice_29/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:220] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
W tensorflow/core/common_runtime/executor.cc:1157] 0x2fcb080 Compute status: Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice_30 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_30/tensor_name, save/restore_slice_30/shape_and_slice)]]
Traceback (most recent call last):
  File "deep_q_network.py", line 207, in <module>
    main()
  File "deep_q_network.py", line 204, in main
    playGame()
  File "deep_q_network.py", line 201, in playGame
    trainNetwork(s, readout, h_fc1, sess)
  File "deep_q_network.py", line 110, in trainNetwork
    saver.restore(sess, checkpoint.model_checkpoint_path)
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/training/saver.py", line 1035, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/client/session.py", line 315, in run
    return self._run(None, fetches, feed_dict)
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/client/session.py", line 511, in _run
    feed_dict_string)
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/client/session.py", line 564, in _do_run
    target_list)
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/client/session.py", line 586, in _do_call
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on saved_networks/saved_networks/tetris-dqn-31660000: Not found: saved_networks/saved_networks
	 [[Node: save/restore_slice = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice/tensor_name, save/restore_slice/shape_and_slice)]]
Caused by op u'save/restore_slice', defined at:
  File "deep_q_network.py", line 207, in <module>
    main()
  File "deep_q_network.py", line 204, in main
    playGame()
  File "deep_q_network.py", line 201, in playGame
    trainNetwork(s, readout, h_fc1, sess)
  File "deep_q_network.py", line 106, in trainNetwork
    saver = tf.train.Saver()
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/training/saver.py", line 785, in __init__
    restore_sequentially=restore_sequentially)
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/training/saver.py", line 455, in build
    filename_tensor, vars_to_save, restore_sequentially, reshape)
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/training/saver.py", line 213, in _AddRestoreOps
    values = self.restore_op(filename_tensor, vs, preferred_shard)
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/training/saver.py", line 128, in restore_op
    preferred_shard=preferred_shard)
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/ops/io_ops.py", line 193, in _restore_slice
    preferred_shard, name=name)
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/ops/gen_io_ops.py", line 271, in _restore_slice
    preferred_shard=preferred_shard, name=name)
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/framework/ops.py", line 2040, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/framework/ops.py", line 1087, in __init__
    self._traceback = _extract_stack()

envy@ub1404:/media/envy/data1t/os_prj/github/_deepmind/DeepLearningVideoGames$

**Comment by gclsoft** [comment]
me too on mac
